2019-05-22 11:18:01,537 - requests - ERROR - sendMail  - 59 - 邮件发送失败
Traceback (most recent call last):
  File "C:/Users/DG02/PycharmProjects/RequestsTestDemo/Common/sendMail.py", line 53, in send_mail
    server.login(email, password)  # 括号中对应的是发件人邮箱账号、邮箱密码
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
2019-05-22 11:18:25,027 - requests - ERROR - base  - 72 - 读取配置报错
Traceback (most recent call last):
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 788, in get
    value = d[option]
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\collections\__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\collections\__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DG02\PycharmProjects\RequestsTestDemo\Common\base.py", line 69, in config_read
    config_get = config.get(section, key)
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'username' in section: 'sender'
2019-05-22 11:18:25,959 - requests - ERROR - sendMail  - 59 - 邮件发送失败
Traceback (most recent call last):
  File "C:/Users/DG02/PycharmProjects/RequestsTestDemo/Common/sendMail.py", line 53, in send_mail
    server.login(email, password)  # 括号中对应的是发件人邮箱账号、邮箱密码
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Users\DG02\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
